### ISSUE TITLE
Release 0.1.1 of Python client

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast#307]
- [x] Update changelog to describe changes since 0.1.0 (#308)
- [x] Rebuild all documentation and proofread for typos (#308)
- [x] Change version number in setup.py and the Sphinx config file (#308)
- [x] Build new package dists
- [x] test installation and verify shapefiles for MSA work
- [x] Upload to PyPI
- [ ] Announce to API mailing list

**Comment by chinandrew** [comment]
@capnrefsmmat do we need that last bullet point, and if so, what are the steps required?

**Comment by capnrefsmmat** [comment]
For major feature releases, we'd send an email to the API mailing list flaunting the new features. Not sure if this release counts as a big one, but in the future we can prep an email like that and send it.

**Comment by krivard** [comment]
0.1.2 was announced today, so closing this
