### ISSUE TITLE
covidcast R 0.5.0 release checklist

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast#627]
- [x] Increment the version number in `DESCRIPTION`
- [x] Update `NEWS.md` to describe all new features, bug fixes, and breaking changes since the last version
- [x] Run `devtools::check()` and ensure there are no errors.
- [x] Run `devtools::document()` and then `pkgdown::build_site()`.
- [x] Browse the generated documentation site and ensure there are no problems.
- [x] Commit the updated HTML. Make sure you don't miss any new plot files!
- [x] Open [a pull request to merge the release branch to `main`](https://github.com/cmu-delphi/covidcast/pull/628) and request review.
