### ISSUE TITLE
covidcast Python release 0.2.1 checklist 

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast#631]
- [x] Increment the package version in `setup.py` and in Sphinx's `docs/conf.py`
- [x] Update `docs/changelog.rst`
- [x] Install the package and its dependencies locally with `make install`
- [x] Rebuild the documentation with `make sphinx`
- [x] Commit the documentation, open a PR, get it approved
- [x] Build the release artifacts with `make build`
- [x] Upload to PyPI
